### ISSUE TITLE
Error in itkSoftwareGuide: Chapter 2.7.3 BilateralFilter Equation 2.18 and 2.19

### ISSUE THREAD

**Issue by 4lexty** [InsightSoftwareConsortium/ITKSoftwareGuide#146]
### Description
In the current itkSoftwareGuide, formulas 2.18 and 2.19 each lack the minus in the exponent so that they are Gaussian kernels.
In addition, equation 2.19 is missing bracket.

### Expected information
As I understand it, this file must be corrected.
[https://github.com/InsightSoftwareConsortium/ITK/blob/master/Examples/Filtering/BilateralImageFilter.cxx](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Examples/Filtering/BilateralImageFilter.cxx)

### Versions
May 25, 2020

### Screenshot
![itk_doc_issue](https://user-images.githubusercontent.com/67057213/85567961-92c10f00-b631-11ea-98f1-26c951275b7c.PNG)

**Comment by dzenanz** [comment]
A [pull request to fix this](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md) should not be hard for someone with knowledge of LaTeX.

**Comment by jhlegarreta** [comment]
Awesome @4lexty , welcome to ITK !

In order to open a PR, you will need to first fork the repository to your own github worspace.

You will then need to configure your fork as the remote repository to push to from your terminal, e.g.:
```
$ git remote set-url origin https//github.com/4lexty/ITKSoftwareGuide.git
```

Also add the upstream repisitory to keep your local copy up-to-date in the future:
```
$ git remote add upstream https//github.com/InsightSoftwareConsortium/ITKSoftwareGuide.git
```

We never push to the main/master branch directly, but create separate branches, do the review and editions on those branches, then merge into main/master when they are ready.

So once you have done the work in a new branch:
```
$ git checkout -b my_feature_branch origin/master
(do my editions)
git add my_edited_file
git commit
```

You'd then push the branch to your fork:
```
$ git push origin my_branch_name
```

And github would automatically suggest to open a PR in the upstream repository (i.e. here).
