### ISSUE TITLE
Broken link in Appendix B Coding Style Guide

### ISSUE THREAD

**Issue by addisonElliott** [InsightSoftwareConsortium/ITKSoftwareGuide#23]
Link to itkTestDriver is broken in Appendix B under section "Naming Tests"

Here is the link that I am referring to:
https://itk.org/ITKSoftwareGuide/html/Book1/ITKSoftwareGuide-Book1ch12.html#x52-210000B.6.4
I did a basic google search to see if I could find what it is supposed to link to but I am not sure.

In Github, here is the link to the code:
https://github.com/InsightSoftwareConsortium/ITKSoftwareGuide/blob/master/SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex#L616

The link is apparently referencing **TestDriver**

**Comment by jhlegarreta** [comment]
@addisonElliott Are you sure that the [line](https://github.com/InsightSoftwareConsortium/ITKSoftwareGuide/blob/e6fa9cd9d55ccb490c099326d58b5c796d97ddc5/SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex#L616) you are referring to corresponds to the broken link you meant?

The ITK SoftwareGuide `code` command is [defined](https://github.com/InsightSoftwareConsortium/ITKSoftwareGuide/blob/master/Latex/Insight.sty) as
```
\newcommand{\code}[1]{\textrm{\@vobeyspaces\@noligs\def\{{\char`\{}\def\}{\char`\}}\def\~{\char`\~}\def\^{\char`\^}\def\e{\char`\\}\def\${\char`\$}\def\#{\char`\#}\def\&{\char`\&}\def\%{\char`\%}%
\texttt{#1}}}
```
and hence it is not intended to provide a link, just to change the font of the text to highlight it/mark it as a mention to code.

You can check in the ITK project/Doxygen  doc that there is no such `itk::TestDriver` class.

Instead, what is meant by that is that `TestDriver` is the way ITK handles tests: due to the large number of classes and corresponding tests, these are **grouped** under the same project for each ITK **module**. Thus, the ITK requires some mechanism to detect the target. This is done by [defining](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CMake/ITKModuleTest.cmake) some special syntax that is used in the `CMakeLists.txt` file of the test project.

This is **explained** (at least the authors tried to do so to the best of their ability) in section **9.4 Tests** of the Software Guide.

Such mechanism was required because having a single project for each class' test makes the number of projects be unmanageable for some compilers.

@thewtex  @fbudin69500 @iMichka @blowekamp @addisonElliott if you happen to have suggestions to make this be clearer, please post them. I'd be happy to introduce the necessary changes.

Otherwise, I'm closing this issue in one week.

**Comment by jhlegarreta** [comment]
No comments were made, so I'm closing the issue.

**Comment by thewtex** [comment]
@addisonElliott Thanks for the note and @jhlegarreta thanks for the explanation and suggestions. I added a link to the test driver description in the appendix in #55 .
